### ISSUE TITLE
Sapflow Sensors To Check

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-sapflow#12]
### PNNL_11
- [ ] C16 - Beech (Port 5)  **hornet making a hive in there, be careful, but the sensors look OK**
- [ ] C18 - Beech (Port 6)  **end of day, couldn't find this, sorry**

### PNNL_12
- [ ] C6 - Tulip (Port 2)  **sensors hanging down; re-inserted and taped**
- [ ] C9 - Maple (Port 3)  **bent probes, sent you a photo**

### PNNL_13
- [ ] C1 - Tulip (Port 1)  **shield gone entirely; made a new one and mounted**
- [ ] C2 - Tulip (Port 2)  **looks OK at tree and in box**
- [ ] C4 - Tulip (Port 3)  **shield off tree; re-mounted**

### PNNL_21
NONE :)

### PNNL_22
- [ ] F6 - Tulip (Port 2)  **shield torn off; remounted with new tape and putty**

### PNNL_23
- [ ] F2 - Tulip (Port 1)  **looks OK at tree and in box except no ground wire**

### PNNL_31
- [ ] S2 - Tulip (Port 1)  **red probe bent slightly, a lot of weight on probes; taped up**
- [ ] S13 - Beech (Port 3)  **probes being pulled downward; taped**

### PNNL_32
- [ ] S1 - Tulip (Port 1)  **probes and shield OK; box OK**
- [ ] S4 - Tulip (Port 2)  **red probe bent 45 degrees; re-inserted snugly**
- [ ] S7 - Maple (Port 3)  **looked OK**

### PNNL_33
NONE :)

### PNNL_41
- [ ] L2 - Maple (Port 2)  **shield on ground; re-mounted with new tape and putty**
- [ ] L3 - Maple (Port 3)  **shield on ground; re-mounted with new tape and putty**

**Comment by bpbond** [comment]
Should I print this out for Thursday?

**Comment by stephpenn1** [comment]
Not yet, these are just port #s.  I need some pages in my data notebook to link

**Comment by stephpenn1** [comment]
Okay @bpbond , this is now updated with the Tree number, species, and port. If you could check at SERC this week for any glaring issues with these sensors and make a note/do any on the spot fixes (sensor bent, unplugged, etc.). And I can come in June to do major maintenance. Thanks so much!

**Comment by bpbond** [comment]
OK will do

**Comment by bpbond** [comment]
@stephpenn1 in addition to your notes above, went through and visually inspected all probes. Problems:

C3 - shield off on ground; re-mounted with new tape and putty
C10 - hanging heavily, taped up
C13 - hanging heavily, probes being pulled downward; taped up
F1 - red probe angled 45 degrees down
F4 - red probe slightly loose; re-inserted
F11 - wires severed, green out, red bent
