### ISSUE TITLE
Where is the sapflow inventory for dataloggers??

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-sapflow#13]
I think in a lab notebook. This needs to be uploaded to GitHub ASAP

**Comment by bpbond** [comment]
Is this the green notebook? What am I looking for exactly?

**Comment by stephpenn1** [comment]
Yes, there should be a few pages of Port numbers with corresponding Tree #s and logger names

**Comment by stephpenn1** [comment]
Found it! https://github.com/PNNL-PREMIS/PREMIS-sapflow/blob/master/SERC/ports.csv
