### ISSUE TITLE
Applying a function to groups

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-sapflow#15]
#### Goal: to apply the `compute_lag_cor()` function to each grouped `Tree` in the `combined` dataset and have the result be a list of n = number of groups tibbles of correlation 0-23 hours

The `group_map` function seems just what i need but i don't understand how to properly use it.. 

```
group_map {dplyr} | R Documentation


Description
group_map(), group_modify() and group_walk() are purrr-style functions that can be used to iterate 
on grouped tibbles.

.tbl | A grouped tibble

.f | A function or formula to apply to each group. It must return a data frame.

If a function, it is used as is. It should have at least 2 formal arguments.
```

Seems straightforward-enough... but I think im having trouble since it's a user-written function. Do you have any experience with it? I'm trying to avoid splitting the dataframe up and doing this separately.

**Comment by bpbond** [comment]
I don't think you need to be that fancy. If `compute_lag_cor()` takes two vectors and returns a third vector, then you can just use `dplyr::do` for example. You can also use the `purrr` package but I don't have much experience with that.

```R
x %>%
  group_by(Tree) %%
  do(tibble(cor = compute_lag_cor(Js, Rs)))
```

Note though that `do` has been superseded in dplyr 1.0. Still, it should work fine.

**Comment by stephpenn1** [comment]
Nice, I haven't used `do` before. Thanks!
