### ISSUE TITLE
Are we even using the correct PAR data?

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-sapflow#17]
- [x] Do we want to only subset with daytime data? Probably
 - [x] What’s this function what Colin found?

 First, let's take PAR vals from NEON and create histogram, look at ranges for daytime

**Comment by stephpenn1** [comment]
Raw PAR data from NEON, interesting seasonal cycles in PAR... you can see how leaf-out impacts the sensor readings each April

![NEON Time Series - DP1 00024 001 - Photosynthetically active radiation (PAR) - SERC](https://user-images.githubusercontent.com/20341158/89228491-b28f0f80-d5ad-11ea-904c-c80b6132f61f.png)

**Comment by stephpenn1** [comment]
Next, I wanted to see whether we still get day-to-day variation even with a dampened reading.. so I zoomed in on June 2020 data and cross-referenced it with the actual weather recorded those month. I do see some good correlation between PAR vals < 50 and days with precip (pretty cool!). Interested in your thoughts on all the above, @bpbond, before I move forward and look at a histogram distribution of the whole dataset

**Comment by bpbond** [comment]
Colin's package is [suncalc](https://cran.r-project.org/web/packages/suncalc/suncalc.pdf).

**Comment by bpbond** [comment]
>good correlation between PAR vals < 50 and days with precip

That is cool!

>leaf-out impacts the sensor reading

Hmm, are the PAR data you pulled below-canopy PAR? Normally when we say "PAR", we mean above-canopy, which is what we'll want for Rs-Js. And that shouldn't be affected by leaf-out. 😕

**Comment by bpbond** [comment]
Hmm, from `NEON.D02.SERC.DP1.00024.001.sensor_positions.20200731T021441Z.csv`:

HOR.VER | name | description
-- | -- | --
0.01 | CFGLOC101567 | Smithsonian Environmental PAR Radiation and IR Biological Temp L1
0.02 | CFGLOC101572 | Smithsonian Environmental PAR Radiation and IR Biological Temp L2
0.03 | CFGLOC101577 | Smithsonian Environmental PAR Radiation and IR Biological Temp L3
0.04 | CFGLOC101582 | Smithsonian Environmental PAR Radiation and IR Biological Temp L4
0.05 | CFGLOC101587 | Smithsonian Environmental PAR Radiation and IR Biological Temp L5
0.06 | CFGLOC101592 | Smithsonian Environmental PAR Radiation Up
0.06 | CFGLOC101593 | Smithsonian Environmental PAR Radiation Down

**Comment by stephpenn1** [comment]
Yeah, I found this document to be not very informative or intuitive. I contacted NEON back in February about this but didn't really get a definite answer.. or at least it was confusing to _me_
<img width="659" alt="Screen Shot 2020-08-04 at 10 17 46 AM" src="https://user-images.githubusercontent.com/20341158/89304862-f4669700-d63b-11ea-95cd-e432317c8f77.png">

**Comment by bpbond** [comment]
My guess is we want `CFGLOC101592` - upward-facing PAR. Is that in your download?

**Comment by stephpenn1** [comment]
Snap - you're right about the sensor position in that graph. I'm using the visualizer on the NEON website and I had the lowest one clicked. Looks like these are the options online. Checking what I have downloaded right now...
![Screen Shot 2020-08-04 at 10 43 06 AM](https://user-images.githubusercontent.com/20341158/89307925-a5bafc00-d63f-11ea-8505-587071a850f0.png)

**Comment by bpbond** [comment]
Awesome. Basically I think we want the highest available upward-facing sensor. Interesting (if a bit frustrating) to learn this!

**Comment by stephpenn1** [comment]
Ah! Wow that photo i just shared of the elevations was the first time I've seen the vertical positions explicitly explained. I'm using `.010` aka the lowest. I think back in February I guessed that the highest position was either the first one or the last one and i chose the first arbitrarily/incorrectly . How high are the trees at SERC you'd say?

**Comment by bpbond** [comment]
The biggest maybe 25-30m?

**Comment by stephpenn1** [comment]
Okay. Should we still go for the highest sensor level then?

**Comment by stephpenn1** [comment]
Renaming this issue, going to start a new one to look at the **correct** PAR data :)

**Comment by bpbond** [comment]
@stephpenn1 Yes I think so. Highest upward-facing sensor.
