### ISSUE TITLE
What do PAR values actually look like at SERC?

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-sapflow#19]
Main goals are to figure out:
- How the data is distributed at SERC
- How we should partition the ranges for sunny/cloudy

**Comment by stephpenn1** [comment]
## How PAR is distributed
- _this is sensor position 5 at SERC; elevation is 73.86 meters_
- _2018-05-01 to 2019-12-31_

**Takeaways from these plots**
- near zero values definitely dominate the data and by splitting the entire dataset into thirds, our "cloudy" matches are most likely based on nighttime PAR
- hourly averaged values seem to stay near zero until ~10am
- amplitude changes over the months as expected but the peak PAR occurs between 6 and 7pm (a surprise to me)
- I think this is pretty useful to know when we discuss when to decide "nighttime" values for the sunny/cloudy comparisons

### Total
![image](https://user-images.githubusercontent.com/20341158/89431428-ea14cd80-d70d-11ea-97fa-133ea495e890.png)

### By hour and month
![image](https://user-images.githubusercontent.com/20341158/89429830-0b74ba00-d70c-11ea-8d1b-cd9e7f600c60.png)

**Comment by stephpenn1** [comment]
@bpbond I'm curious of your thoughts on this and would like to discuss how we should partition daytime from nighttime, should we:
- [ ] use sunset and sunrise time from `suncalc`
- [ ] use average times, 6a/8p
- [ ] do some sort of "filter" of the extremely low values

**Comment by bpbond** [comment]
Neat! 👏  Like that hour and month graph.

I definitely vote for screening out nighttimes, because it doesn't make any sense to include those data when making a sunny-vs-cloudy comparison. And if we're going to do that, let's do it right, using `suncalc` or something like it.
