### ISSUE TITLE
Battery/Power Maintenence

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-sapflow#2]
- [x] Top batteries off with deionized water every few months (4-6 months)
- [x] Tape over battery terminals
- [x] Strap battery cases closed to prevent animal burrowing
- [x] Clamp ground rods to earth ground
- [x] Find alternate method for battery clamps

**Comment by bpbond** [comment]
Did the last yesterday.

**Comment by stephpenn1** [comment]
Thanks @bpbond !
