### ISSUE TITLE
Dendrometers

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-sapflow#3]
From my email to James and Nate:

>How many do we want? I assume, as a bare minimum, enough to cover the current sapflux trees, but we originally told them a couple hundred. If we want that many, it would allow putting bands on 50-75% of the trees in the three big plots.

**Comment by stegen** [comment]
I don't know what's involved in installing these or recording data, maintance, etc. If they are high thoughoutput and easy to maintain, etc., and if there aren't major downsidies, then having more trees instrumented sure seems great to me.
